awesome-book with es6
frnega/awesom-book-es6new pull request #1
Opened 2022-11-08 08:20 UTC by frnega

in this project added all the required files

2022-11-08 16:25 UTC, bellom requested changes
@frnega - 

### This is a manual review

Kindly let me know if you don't have it working like this, if you do, kindly fix it.

Kindly compare your design to the wireframe provided.

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/31897434/200612599-5477f2c9-f9f2-4ebb-83bb-6289107581db.png">

Cheers and Happy coding!:clap::clap::clap:

2022-11-08 16:44 UTC, frnega commented on index.html
> +    <!-- <hr class="line"> -->
@bellom  this is what I see it works as required
![awsom-book](https://user-images.githubusercontent.com/101171478/200624335-b11ce0e2-bcd6-413d-a181-0c40a73e2770.PNG)

removed the comments both from index.html and index.css

2022-11-09 09:13 UTC, frnega commented
@bellom  
the page works perfectly do you want a video demo I do not understand the question you asked when you click the page it goes to the desired page. you have to change to the new branch and click on GO LIVE in your visual code to see it on your browser.

![list](https://user-images.githubusercontent.com/101171478/200788604-658a1146-7e22-4024-8b40-d0fb0ab17710.PNG)

![add new](https://user-images.githubusercontent.com/101171478/200788972-45998494-a0ec-4830-b551-950bf38b9177.PNG)


![contact](https://user-images.githubusercontent.com/101171478/200788704-2c03936b-1386-42b9-af30-e7b9431f760a.PNG)

2022-11-09 09:58 UTC, bellom commented on index.html
> +    <!-- <hr class="line"> -->
> @bellom this is what I see it works as required ![awsom-book](https://user-images.githubusercontent.com/101171478/200624335-b11ce0e2-bcd6-413d-a181-0c40a73e2770.PNG)
> 
> removed the comments both from index.html and index.css

@frnega,

I appreciate that you confirmed it here, we should not be seeing two different links whenever the page is loaded, in this screenshot, I can see a list of books and also the book form. do you agree with me?

if yes, once we reload the page, let's show either the book form or the list of books but not both.

I hope this is clear now.

2022-11-09 10:31 UTC, frnega commented
@bellom <https://github.com/bellom>

ok now I understand, I removed the book list part now only see the list of
books page.
https://github.com/frnega/awesom-book-es6new/pull/1


On Wed, Nov 9, 2022, 12:58 PM Oluwaseun Bello ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/frnega/awesom-book-es6new/pull/1#discussion_r1017719124>
> :
>
> > +                <li ><a class="link listofbook" href="#">List</a></li>
> +                <li ><a class="link addbookform" href="#">Add new</a></li>
> +                <li ><a class="link contactInfo" href="#">Contact</a></li>
> +            </ul>
> +        </nav>
> +    </header>
> +    <div class="time-div"></div>
> +
> + <main>
> +<div class="awesomebooks">
> +<section class="displayed-books" id="displayed-books">
> +    <h2 class="headingmain">All awesome books</h2>
> +        <ul id="book-list"></ul><br>
> +</section>
> +<section class="add-awesombooks">
> +    <!-- <hr class="line"> -->
>
> @bellom <https://github.com/bellom> this is what I see it works as
> required [image: awsom-book]
> <https://user-images.githubusercontent.com/101171478/200624335-b11ce0e2-bcd6-413d-a181-0c40a73e2770.PNG>
>
> removed the comments both from index.html and index.css
>
> @frnega <https://github.com/frnega>,
>
> I appreciate that you confirmed it here, we should not be seeing two
> different links whenever the page is loaded, in this screenshot, I can see
> a list of books and also the book form. do you agree with me?
>
> if yes, once we reload the page, let's show either the book form or the
> list of books but not both.
>
> I hope this is clear now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/frnega/awesom-book-es6new/pull/1#discussion_r1017719124>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYD4CFQ764EMCEVHLBJ6ILTWHNYV3ANCNFSM6AAAAAAR2BABZI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-11-09 11:28 UTC, merged